spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cooltalkdb?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 656565
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081  # ??
  servlet:
    context-path: /  # ???????????????????
    session:
      timeout: 3600  # ?????session?????????
